# Generated by Django 5.1.3 on 2025-01-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(default='BTCUSDC', max_length=30)),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField()),
                ('open_amount', models.DecimalField(decimal_places=50, max_digits=200)),
                ('high', models.DecimalField(decimal_places=50, max_digits=200)),
                ('low', models.DecimalField(decimal_places=50, max_digits=200)),
                ('close_amount', models.DecimalField(decimal_places=50, max_digits=200)),
            ],
        ),
    ]
