# Generated by Django 5.1.3 on 2025-02-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_investmentplan_mpesacallback_investment'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentplan',
            name='description',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='name',
            field=models.CharField(choices=[('AMATUER', 'AMATUER'), ('BEGINNER', 'BEGINNER'), ('INTERMIDIATE', 'INTERMIDIATE'), ('LEGENDARY', 'LEGENDARY'), ('PRO', 'PRO')], max_length=50, unique=True),
        ),
    ]
