# Generated by Django 5.1.3 on 2025-05-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_profile_profile_pic_alter_wallet_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='user/profile_pics/32x32.png', upload_to='user/profile_pics'),
        ),
    ]
