# Generated by Django 5.1.3 on 2025-05-14 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdrawal',
            old_name='completed',
            new_name='is_completed',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='is_cancelled',
        ),
    ]
