# Generated by Django 5.1.3 on 2025-05-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_rename_completed_withdrawal_is_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='status',
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='is_completed',
            field=models.IntegerField(default=0),
        ),
    ]
