# Generated by Django 5.1.3 on 2025-05-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_depo_verification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='user',
        ),
        migrations.AddField(
            model_name='investment',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investment',
            name='return_percentage',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_terms_modal',
            field=models.BooleanField(default=True),
        ),
    ]
