# Generated by Django 5.1.3 on 2025-06-07 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_remove_investment_return_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='end_date',
        ),
    ]
