# Generated by Django 5.1.3 on 2025-06-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_remove_investment_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='db_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
