# Generated by Django 5.1.3 on 2025-06-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_investment_db_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='balance_usd',
            field=models.CharField(default='0.00', max_length=20),
        ),
        migrations.AlterField(
            model_name='investmentplan',
            name='name',
            field=models.CharField(choices=[('Alpha Return CFD', 'Alpha Return CFD'), ('Rapid Growth CFD', 'Rapid Growth CFD'), ('CryptoFortress_CFD', 'CryptoFortress_CFD'), ('AI-Powered_Profit_CFD', 'AI-Powered_Profit_CFD'), ('Freedom_Fund_CFD', 'Freedom_Fund_CFD'), ('Lagacy_Builder_CFD', 'Lagacy_Builder_CFD'), ('Platimum_Wealth_CFD', 'Platimum_Wealth_CFD'), ('SmartReturns_Algorithm', 'SmartReturns_Algorithm'), ('Compounding_Fortune_CFD', 'Compounding_Fortune_CFD')], max_length=50, unique=True),
        ),
    ]
