# Generated by Django 5.1.3 on 2025-06-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_wallet_balance_usd_alter_investmentplan_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance_usd',
            field=models.CharField(blank=True, default='0.00', max_length=20, null=True),
        ),
    ]
