# Generated by Django 5.1.3 on 2025-06-21 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_wallet_balance_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investmentplan',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
