# Generated by Django 5.2.9 on 2025-12-29 09:47

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_emailsender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='start_date',
        ),
        migrations.AddField(
            model_name='investment',
            name='days_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='investment',
            name='db_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='last_profit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='profit_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='investment',
            name='total_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='investment',
            name='total_payout',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='investment',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.investmentplan'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paid', 'Paid Out')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='investment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('investment', 'Investment'), ('trade', 'Trade'), ('exchange', 'Exchange'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('balance_before', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('pending', 'Pending'), ('failed', 'Failed')], default='success', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to='dashboard.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='dashboard_t_user_id_1c18fc_idx'), models.Index(fields=['transaction_type'], name='dashboard_t_transac_0e0bc4_idx'), models.Index(fields=['status'], name='dashboard_t_status_7b0a67_idx'), models.Index(fields=['reference_id'], name='dashboard_t_referen_9712a5_idx')],
            },
        ),
    ]
