# Generated by Django 5.2.9 on 2026-01-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_remove_investment_duration_minutes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawal',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
