# Generated by Django 5.2.9 on 2026-01-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_add_profile_complete_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
