# Generated by Django 5.2.9 on 2026-01-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_fix_profile_complete_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposittransaction',
            name='checkout_request_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deposittransaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
