# Generated by Django 5.2.10 on 2026-01-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_securitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
