# Generated by Django 5.2.10 on 2026-02-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('2fa_enabled', '2FA Enabled'), ('2fa_disabled', '2FA Disabled')], max_length=50),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
