# Generated by Django 5.2.10 on 2026-02-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_alter_securitylog_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securitylog',
            name='action',
            field=models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('withdrawal_request', 'Withdrawal Request'), ('profile_update', 'Profile Update'), ('wallet_update', 'Wallet Update'), ('2fa_enable', '2FA Enabled'), ('2fa_disable', '2FA Disabled'), ('deposit_initiated', 'Deposit Initiated'), ('deposit_completed', 'Deposit Completed'), ('investment_created', 'Investment Created'), ('investment_completed', 'Investment Completed'), ('trade_executed', 'Trade Executed')], max_length=50),
        ),
    ]
