# Generated by Django 5.2.9 on 2026-03-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_alter_securitylog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_to_kes', models.DecimalField(decimal_places=4, help_text='Number of KES per 1 USD (e.g. 130.5000)', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Only one rate should be active at a time.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, help_text="Optional note, e.g. 'Updated from CBK rate 2026-03-21'", max_length=255)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
